version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    env_file: .env

  mongo-express:
    image: mongo-express
    ports:
      - 127.0.0.1:8082:8081
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://mongo:27017/$MONGO_DATABASE"]
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
